# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/boiler.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/boiler.proto'
)
# @@protoc_insertion_point(imports)
_sym_db = _symbol_database.Default()
DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/boiler.proto\x12\x06\x62oiler\"\x07\n\x05\x45mpty\"w\n\x0c\x42oilerStatus\x12\x11\n\ttimestamp\x18\x01 \x01(\x01\x12\x14\n\x0c\x66urnace_temp\x18\x02 \x01(\x01\x12\x16\n\x0esteam_pressure\x18\x03 \x01(\x01\x12\x12\n\ndrum_level\x18\x04 \x01(\x01\x12\x12\n\nsteam_flow\x18\x05 \x01(\x01\"P\n\x0c\x43ontrolInput\x12\x12\n\nfuel_valve\x18\x01 \x01(\x01\x12\x17\n\x0f\x66\x65\x65\x64water_valve\x18\x02 \x01(\x01\x12\x13\n\x0bsteam_valve\x18\x03 \x01(\x01\x32|\n\rBoilerPhysics\x12\x30\n\tGetStatus\x12\r.boiler.Empty\x1a\x14.boiler.BoilerStatus\x12\x39\n\x0bSetControls\x12\x14.boiler.ControlInput\x1a\x14.boiler.BoilerStatusb\x06proto3')
_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.boiler_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=30
  _globals['_EMPTY']._serialized_end=37
  _globals['_BOILERSTATUS']._serialized_start=39
  _globals['_BOILERSTATUS']._serialized_end=158
  _globals['_CONTROLINPUT']._serialized_start=160
  _globals['_CONTROLINPUT']._serialized_end=240
  _globals['_BOILERPHYSICS']._serialized_start=242
  _globals['_BOILERPHYSICS']._serialized_end=366
# @@protoc_insertion_point(module_scope)
