// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: boiler.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_boiler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_boiler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_boiler_proto_rawDescGZIP(), []int{0}
}

type BoilerStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     float64                `protobuf:"fixed64,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	FurnaceTemp   float64                `protobuf:"fixed64,2,opt,name=furnace_temp,json=furnaceTemp,proto3" json:"furnace_temp,omitempty"`
	SteamPressure float64                `protobuf:"fixed64,3,opt,name=steam_pressure,json=steamPressure,proto3" json:"steam_pressure,omitempty"`
	DrumLevel     float64                `protobuf:"fixed64,4,opt,name=drum_level,json=drumLevel,proto3" json:"drum_level,omitempty"`
	SteamFlow     float64                `protobuf:"fixed64,5,opt,name=steam_flow,json=steamFlow,proto3" json:"steam_flow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoilerStatus) Reset() {
	*x = BoilerStatus{}
	mi := &file_boiler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoilerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoilerStatus) ProtoMessage() {}

func (x *BoilerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_boiler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoilerStatus.ProtoReflect.Descriptor instead.
func (*BoilerStatus) Descriptor() ([]byte, []int) {
	return file_boiler_proto_rawDescGZIP(), []int{1}
}

func (x *BoilerStatus) GetTimestamp() float64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BoilerStatus) GetFurnaceTemp() float64 {
	if x != nil {
		return x.FurnaceTemp
	}
	return 0
}

func (x *BoilerStatus) GetSteamPressure() float64 {
	if x != nil {
		return x.SteamPressure
	}
	return 0
}

func (x *BoilerStatus) GetDrumLevel() float64 {
	if x != nil {
		return x.DrumLevel
	}
	return 0
}

func (x *BoilerStatus) GetSteamFlow() float64 {
	if x != nil {
		return x.SteamFlow
	}
	return 0
}

type ControlInput struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FuelValve      float64                `protobuf:"fixed64,1,opt,name=fuel_valve,json=fuelValve,proto3" json:"fuel_valve,omitempty"`
	FeedwaterValve float64                `protobuf:"fixed64,2,opt,name=feedwater_valve,json=feedwaterValve,proto3" json:"feedwater_valve,omitempty"`
	SteamValve     float64                `protobuf:"fixed64,3,opt,name=steam_valve,json=steamValve,proto3" json:"steam_valve,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ControlInput) Reset() {
	*x = ControlInput{}
	mi := &file_boiler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlInput) ProtoMessage() {}

func (x *ControlInput) ProtoReflect() protoreflect.Message {
	mi := &file_boiler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlInput.ProtoReflect.Descriptor instead.
func (*ControlInput) Descriptor() ([]byte, []int) {
	return file_boiler_proto_rawDescGZIP(), []int{2}
}

func (x *ControlInput) GetFuelValve() float64 {
	if x != nil {
		return x.FuelValve
	}
	return 0
}

func (x *ControlInput) GetFeedwaterValve() float64 {
	if x != nil {
		return x.FeedwaterValve
	}
	return 0
}

func (x *ControlInput) GetSteamValve() float64 {
	if x != nil {
		return x.SteamValve
	}
	return 0
}

var File_boiler_proto protoreflect.FileDescriptor

const file_boiler_proto_rawDesc = "" +
	"\n" +
	"\fboiler.proto\x12\x06boiler\"\a\n" +
	"\x05Empty\"\xb4\x01\n" +
	"\fBoilerStatus\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x01R\ttimestamp\x12!\n" +
	"\ffurnace_temp\x18\x02 \x01(\x01R\vfurnaceTemp\x12%\n" +
	"\x0esteam_pressure\x18\x03 \x01(\x01R\rsteamPressure\x12\x1d\n" +
	"\n" +
	"drum_level\x18\x04 \x01(\x01R\tdrumLevel\x12\x1d\n" +
	"\n" +
	"steam_flow\x18\x05 \x01(\x01R\tsteamFlow\"w\n" +
	"\fControlInput\x12\x1d\n" +
	"\n" +
	"fuel_valve\x18\x01 \x01(\x01R\tfuelValve\x12'\n" +
	"\x0ffeedwater_valve\x18\x02 \x01(\x01R\x0efeedwaterValve\x12\x1f\n" +
	"\vsteam_valve\x18\x03 \x01(\x01R\n" +
	"steamValve2|\n" +
	"\rBoilerPhysics\x120\n" +
	"\tGetStatus\x12\r.boiler.Empty\x1a\x14.boiler.BoilerStatus\x129\n" +
	"\vSetControls\x12\x14.boiler.ControlInput\x1a\x14.boiler.BoilerStatusB\x16Z\x14plc-service/pkg/grpcb\x06proto3"

var (
	file_boiler_proto_rawDescOnce sync.Once
	file_boiler_proto_rawDescData []byte
)

func file_boiler_proto_rawDescGZIP() []byte {
	file_boiler_proto_rawDescOnce.Do(func() {
		file_boiler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_boiler_proto_rawDesc), len(file_boiler_proto_rawDesc)))
	})
	return file_boiler_proto_rawDescData
}

var file_boiler_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_boiler_proto_goTypes = []any{
	(*Empty)(nil),        // 0: boiler.Empty
	(*BoilerStatus)(nil), // 1: boiler.BoilerStatus
	(*ControlInput)(nil), // 2: boiler.ControlInput
}
var file_boiler_proto_depIdxs = []int32{
	0, // 0: boiler.BoilerPhysics.GetStatus:input_type -> boiler.Empty
	2, // 1: boiler.BoilerPhysics.SetControls:input_type -> boiler.ControlInput
	1, // 2: boiler.BoilerPhysics.GetStatus:output_type -> boiler.BoilerStatus
	1, // 3: boiler.BoilerPhysics.SetControls:output_type -> boiler.BoilerStatus
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_boiler_proto_init() }
func file_boiler_proto_init() {
	if File_boiler_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_boiler_proto_rawDesc), len(file_boiler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_boiler_proto_goTypes,
		DependencyIndexes: file_boiler_proto_depIdxs,
		MessageInfos:      file_boiler_proto_msgTypes,
	}.Build()
	File_boiler_proto = out.File
	file_boiler_proto_goTypes = nil
	file_boiler_proto_depIdxs = nil
}
